### PR TITLE
Use latest cvelint + other CI improvements

### PR DESCRIPTION
**Pull request by mprpic**

### CODE REVIEW

**Comment by jgamblin** [comment]
Thanks for the update.  I will figure out the piping error.

**Comment by mprpic** [comment]
Ah, I thought that was an error in my instance of the repo only because I didn't have the secret set, but I guess it was the pipe. I originally had it in there because without it the log prints each "Processed N records..." line separately, producing huge output (in a normal terminal the line gets overwritten on every update).

**Comment by jgamblin** [comment]
Something strange is happening with GitHub actions. I can run the updated CVELint in a container fine, but running it as an action always fails regardless of the piping. 

Here are the last few lines of the run: 

```
2024-04-02T13:09:10.4781011Z Processed 243736 CVE records...
2024-04-02T13:09:10.4781106Z Processed 243737 CVE records...
2024-04-02T13:09:10.4781214Z Processed 243738 CVE records...
2024-04-02T13:09:10.4781308Z Processed 243739 CVE records...
2024-04-02T13:09:11.0812666Z Processed 243740 CVE records...
2024-04-02T13:09:12.2128634Z [K
2024-04-02T13:09:12.2140189Z ##[error]Process completed with exit code 1.
2024-04-02T13:09:12.2152188Z ##[debug]Finishing: Run CVELINT
```

I will look at it more and open an issue with the GitHub team if needed.

**Comment by mprpic** [comment]
Ah, now I remember, in 0.2.0 I switched it to return a `1` when there are any error results found: https://github.com/mprpic/cvelint/issues/7. So the CI fails because it thinks cvelint errored out. I think you can have the job ignore any status codes with `continue-on-error: true`:

```
    - name: Run CVELINT
      env:
        GH_TOKEN:  ${{ secrets.GH_TOKEN }}
      run: |
          ./cvelint -format csv ./cvelistV5/cves > CVEV5Errors.csv
          ./cvelint -format json ./cvelistV5/cves > CVEV5Errors.json
      continue-on-error: true
```

**Comment by jgamblin** [comment]
Awesome. Everything is working now, except for posting the JSON file from v0.3, which is now over 100MB. ¯\_(ツ)_/¯ 
Hopefully, some of the CVEs will get cleaned up soon, so that file will be reposted.

**Comment by mprpic** [comment]
Mmm, the version data in the CVE data set just isn't great because of the prevalance of `version=n/a` in older records. If I split it out by error code, the new check for invalid versions (E007) accounts for the majority of errors:
```
> for ecode in $(./bin/cvelint -show-rules | grep -o '^.[0-9]\{3,\}'); do ./bin/cvelint -format csv -select "$ecode" ./cvelistV5/cves/ > "$ecode"-cvev5-errors.csv; done
> ls -s1h E*
4.0K E001-cvev5-errors.csv
812K E002-cvev5-errors.csv
4.0K E003-cvev5-errors.csv
1.4M E004-cvev5-errors.csv
8.0K E005-cvev5-errors.csv
 16K E006-cvev5-errors.csv
 61M E007-cvev5-errors.csv
```
We could also split the errors to individual files by CNA if I add a `-show-cna` option that lists all the CNAs in the given CVE data set. I'm sure that would break it down into smaller files.

Alternatively, the check for E007 could be limited to just CVEs after 2016 or something.

**Comment by jgamblin** [comment]
I personally like limiting the E007 check to after 2016 as the goal is for CNAs to see them and fix the issues.  I doubt anyone is going to go back and correct records older than that.

**Comment by mprpic** [comment]
Welp, because the number of CVEs assigned goes up pretty much exponentially since like 2017, the file is still 31MB even when limited to 2020+. Some CNAs also put 100s of affected components with versions that aren't really versions in their records so that doesn't help either...

Fwiw, this is the run.sh script that I made locally to generate the per-file results:

```bash
#!/usr/bin/env bash

# Generate error reports for each error code separately, except for E007 where there
# are too many errors in old data.
for ecode in $(./bin/cvelint -show-rules | grep -o '.[0-9]\{3,\}' | grep -v E007); do
  ./cvelint -select "$ecode" -format csv ./cvelistV5/cves > "$ecode"-CVEV5Errors.csv
  ./cvelint -select "$ecode" -format json ./cvelistV5/cves > "$ecode"-CVEV5Errors.csv
done

# Generate E007 report for 2016+ CVE.
rm -rf ./cvelistV5/cves/!(201[6-9]|202[0-9])
./cvelint -select E007 -format csv ./cvelistV5/cves > E007-CVEV5Errors.csv
./cvelint -select E007 -format json ./cvelistV5/cves > E007-CVEV5Errors.csv
```

**Pull request merged**
